version: "3"

services:
  auth-service:
    container_name: auth-service
    image: auth-service
    depends_on:
      - nginx
    volumes:
      - ./backend:/var/www/html
  
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs/:/var/log/nginx/
      - ./backend:/var/www/html
  
  mysql:
    container_name: mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: authservice
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
  
  composer:
    image: composer:latest
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
  
  artisan:
    image: auth-service
    entrypoint: ["php", "artisan"]
    working_dir: /var/www/html
    
    depends_on:
      - mysql
    volumes:
      - ./backend:/var/www/html
  
networks:
  default:
    external:
      name: auth-service-network